services:
  vlmcsd:
    build:
      context: https://github.com/Wind4/vlmcsd-docker.git
      dockerfile_inline: |
        FROM alpine:latest as builder
        WORKDIR /root
        RUN apk add --no-cache git make build-base && \
            git clone --branch master --single-branch https://github.com/Wind4/vlmcsd.git && \
            cd vlmcsd/ && \
            make

        FROM alpine:latest
        WORKDIR /root/
        COPY --from=builder /root/vlmcsd/bin/vlmcsd /usr/bin/vlmcsd
        RUN echo S01EAAAAAgAIAQAAAwAAACMAAADqAAAACAAAAAAAAABIAQAAAAAAAKgBAAAAAAAACAYAAAAAAABI \
                 IwAAAAAAAAAAAAAAAAAASCQAAAAAAACA7ipmAAAAADcTAAAgTgAAH3sxAQAAAACWJAAAAAAAAIBP \
                 PkwAAAAAYAAAAMB/3At/av4MAAAAAN8kAAAAAAAAABEHUQAAAADOAAAAgI7yDf8/Qg8AAAAAKCUA \
                 AAAAAAAAmgBWAAAAAM4AAABAFwwav8hbGwAAAABxJQAAAAAAAIAz5FgAAAAAEg8AAMDh5AD/yZo7 \
                 AAAAAMslAAAAAAAAACmoWwAAAADOAAAAgFqyJ3+H4ygAAAAAFCYAAAAAAAAAiUJhAAAAAM4AAADA \
                 xAgiv/E5IwAAAABdJgAAAAAAAAB152YAAAAAzgAAAMDxOSO/HmskAAAAADQnyVWC1nFNmD7W7D8W \
                 BZ+IJwAAAAAAAAAAADIAAAAAgSilWYmpnUevRvJ1xjcGY5AnAAAAAAAAAAAACgAAAQAVzvEPiamd \
                 R69G8nXGNwZjmycAAAAAAAAAAAAKAAAHAGUff5DNrS5KlbxL9QC8blinJwAAAAAAAAAABgUAAAAA \
                 5GNCt5IPxka8+MEdXv4pWbsnAAAAAAAAAAAGBQAAAAD7sUmE6vB6SZmrZsqW6aD1zycAAAAAAAAA \
                 AAYFAAAAAGnAn259JcRLtKd1BRTTJ0PjJwAAAAAAAAAABgUAAAAAJ+de6MRpKEWZ0iFrDwZeOPcn \
                 AAAAAAAAAAAGGQAAAAAXaFc7dXtiQ54TIj8tnpyXECgAAAAAAAAAAAYZAAAAADbWfNJiGelEi08n \
                 tsI++4UpKAAAAAAAAAAABhkAAAAAurHcy5PggUykYxB3UpH9+UIoAAAAAAAAAAAGGQAAAAAjv6B7 \
                 9dByQJHZ1Vr1pIG2YSgAAAAAAAAAAAYBAAAEAFlWsRED5vFMnB/w7AG4GIh9KAAAAAAAAAAABhkA \
                 AAAAwOOfluyjGkmfJUI2Bd6zZZYoAAAAAAAAAAAGGQAAAABPE+JYEY4XTZyykQacFRFIrygAAAAA \
                 AAAAAAYZAAAAAFgTxeE+/gNCpKI7ayDJc07DKAAAAAAAAAAABhkBAAAAu6CUX6DVgUCmhVgZQYsv \
                 4NcoAAAAAAAAAAAGGQABAABwUl9trDE+Q7kKOYkpI8ZX5ygAAAAAAAAAAAYFAAEAAIDHj8sFLFpJ \
                 lxCFr//JBNf+KAAAAAAAAAAABhkAAAAAkGhkbQY2GkaGq1mLuErOghMpAAAAAAAAAAAGGQEAAABY \
                 s0A8SFmvRZI7U9IfzH55KCkAAAAAAAAAAAUZAAAAADt7ubukjChKlxeJ+r1CxKw7KQAAAAAAAAAA \
                 BRkBAAAAGVLef/r7SkiCyTTRrVPoVk4pAAAAAAAAAAAEGQAAAADcZCohsUM9TaMML8adIJXGWCkA \
                 AAAAAAAAAAQZAAAAANPvVoQEDIlAh0BbcjhTWmVmKQAAAAAAAAAABgUAAAAAcctlhoxGo0qjN8ub \
                 ydXqrH0pAAAAAAAAAAAFBQAAAACvzMYPDv+uT50IQ3B4W/ftkSkAAAAAAAAAAAQFAAAAALb1h8pG \
                 zcBAsG2OzVekNz+4KQAAAAAAAAAABAUAAAAAiSbKsqip10KTjc+OnyAZWOspAAAAAAAAAAAEBQAA \
                 AADkVuEzb7dSSp+R9kHdlaxIESoAAAAAAAAAAAQFAAAAAIcz5Y+HMEdEiYX3UTIhWsk1KgAAAAAA \
                 AAAABAUAAAAA8/0hisXL60SD8/4oTmaAp2UqAAAAAAAAAAAEBQAAAABG+VroJS63R4Phvrzr6sYR \
                 iCoAAAAAAAABAAQFAAABAL/xpuZAncNAqp/He6IVeMCUKgAAAAAAAAIABQUAAAIAG/a1hQsy40uB \
                 SrdrK/r8gqAqAAAAAAAAAgAGBQAAAwCxnn1hNu+CT4bgplrge5bGrCoAAAAAAAACAAYFAAAFABYL \
                 1YYISK9BuDuzOCdDGLK4KgAAAAAAAAIABgUAAAYAtTyXqAO/TAqc73AwmWRas8QqAAAAAAAAAgAG \
                 BQAABwDyr7VFoGDyQrxL7G5fe1J+0CoAAAAAAAAAAAYFAAAAANFG6cKizyNFjIcwvGlu5YTvKgAA \
                 AAAAAAAABgUAAAAAZPFSwPbNmkCgy4U7oPD1WhwrAAAAAAAAAAAGBQAAAABJZMJ9IdsJTro3KPKV \
                 hQamOysAAAAAAAAAAAYFAAAAANMKj4xDmgVOuECTuNFHXLxYKwAAAAAAAAABBgUAAAAA++C1GTFE \
                 vEa6wS8Yc+Suc3crAAAAAAAAAAEGBQAAAACf/GzvXYysRJqt3mouoK4DpCsAAAAAAAAAAQYFAAAA \
                 AGB415sxm3tLlq0lZAFzFb/DKwAAAAAAAAABBgUAAAAAQZzmObRCCkqrrY48EKeXzOArAAAAAAAA \
                 AAEGBQAAAACcQun1C/WYS7Fc75LrXP85FSwAAAAAAAAAAQYFAAAAAPDBnKkZdwZDlkUpQQL7/5VI \
                 LAAAAAAAAAACBgUAAAAAuzxNA0tdRUKz+PhFcTFAeGcsAAAAAAAAAAIGBQAAAABVruE0+CdQSYh3 \
                 egO+X7GBhiwAAAAAAAAAAgYFAAAAAP3qMt7uqmJGlETBvvtBveKlLAAAAAAAAAACBgUAAAAAYuvo \
                 jeC7rECsF/dVlQceo8IsAAAAAAAAAAIGBQAAAADlYsOQoQ39S7U7uH0wmt5D3CwAAAAAAAAAAgYF \
                 AAAAAHyV43MM/A1AkYRfe28utAkRLQAAAAAAAAACBgUAAAAAGzS/PWxfp0+5Nmmdzp4mP0QtAAAA \
                 AAAAAAMGBQAAAAAPG1orq6VUTKwvptlIJKKDYy0AAAAAAAAAAwYFAAAAAHlnxSFJtCBNrfzuzg4a \
                 10uCLQAAAAAAAAADBgUAAAAAEFQcjDmfBUiMnWOgdwY1j6EtAAAAAAAAAAMGBQAAAABur9lDhl7o \
                 S6eX0HKgRolsvi0AAAAAAAAAAwYFAAAAAOcInOSC2vhCveK1cPvK52zYLQAAAAAAAAADBgUAAAAA \
                 Iu/FYU/xU0WoJMSzHoSxAA0uAAAAAAAAAAMGBQAAAAD0M0R757GIR4laxFN404JTQC4AAAAAAAAA \
                 AwYFAAAAAGWOhuzf+llHsj6T/jfyzCliLgAAAAAAAAAHBhkAAAAAg9Oy4BLRP0GKgJfzc6WCDIku \
                 AAAAAAAAAAgGAQAABAD7VITjpEFZT6XcJQgONUcwpC4AAAAAAAAACAYBAAAEALP60jKo5MJCkjtL \
                 9P0T5u7BLgAAAAAAAAAJBhkAAAAAM6MDcci4zEmTztN8CWh/ku4uAAAAAAAAAAkGGQAAAABgWlot \
                 QDC/SL6w/NdwwgzgHS8AAAAAAAAACgYZAAAAAINtd59WcbJFilw1m5yfIqM9LwAAAAAAAAAKBhkA \
                 AAAAbKRRewQMj06a9ISWzKkNXl8vAAAAAAAAAAsGGQAAAAC3OLiHtkGQRYMYV5eVHYUpfy8AAAAA \
                 AAAACwYZAAAAAIgixOAMmIhHoBTAgNLhkm6hLwAAAAAAAAALBhkAAAAAVSMQPCfQxkKtIy5++KAl \
                 hbkvAAAAAAAAAAsGGQAAAAAhERFzOFb2QLwR8dew1kMA0y8AAAAAAAAACwYZAAAAAOLjcuIvc2VM \
                 qPBIR0fQ2UfsLwAAAAAAAAALBhkAAAAAknPmLae3KkaxyhCN0Yn1iAcwAAAAAAAAAAsGGQAAAAC/ \
                 WguorXaLQrBdpH0t/+6/GTAAAAAAAAAACwYZAAAAAIL8Gj+s+GxPgAUdIz5gbu4tMAAAAAAAAAAL \
                 BhkAAAAAjLEAUzMuwk2CkUf/zsdG3UkwAAAAAAAAAAsGGQAAAACSwLuCULwWTo4Yt0/Ehq7DZzAA \
                 AAAAAAAACwYZAAAAANNxFUv7ukBLgIepYb4sr2WFMAAAAAAAAAALBhkAAAAAXJbrWVCRt0Kg7CIV \
                 G5iXxaUwAAAAAAAAAAsGGQAAAADj8n3KoF64R5rBsb5Njt1p0TAAAAAAAAAACwYZAAAAAPw2AdNL \
                 y25Boj2HIHq8RKnfMAAAAAAAAAALBhkAAAAAFPj0DVc/i0uanf3a3NafrO8wAAAAAAAAAAsGGQAA \
                 AADqUNvkob1mRbBHDKUKvG8HAzEAAAAAAAAACwYZAAAAAJl86Vh38/FOgdVK1VIrX9gcMQAAAAAA \
                 AAAMBhkBAAAAUReee9qodU+VYF+t/j2OOC8xAAAAAAAAAAwGGQEAAABEdRCpoPRTQKlqFHmr3vkS \
                 RDEAAAAAAAAADAYZAQAAAFeKkc0bpIJMjc4aU44iGoNoMQAAAAAAAAAMBhkBAAAAx1LpzZYvnU2P \
                 Ky00n2T8UYsxAAAAAAAAAA0GGQABAABrPjik2to9QqQ98lZ4QpZ2qzEAAAAAAAAADQYZAAEAAHug \
                 Wc8qGuBLv+BCO1gj5mPNMQAAAAAAAAANBhkAAQAAfzOcKx16cUKQo8aFWiuKHPIxAAAAAAAAAA0G \
                 GQABAAByrR5jq6j4TbvfNyApmJvdDDIAAAAAAAAADQYZAAEAAER8lLqd0YZHtq4idwvJTFQpMgAA \
                 AAAAAAAOBgUAAQAAJCeH0whcG0uR8vyer+1JkEsyAAAAAAAAAA4GBQABAAATb2flZpsfSosMQ0kO \
                 I2ICazIAAAAAAAAADgYFAAEAACy2lbni6qpAr7kRGImoTvSGMgAAAAAAAAAOBgUAAQAArxpngdF5 \
                 sU6wBIy74XOv6qYyAAAAAAAAAA8GGQAAAABccD4RSfqkSL7qfdh5tGsUvTIAAAAAAAAADwYZAAAA \
                 AIFpa8D91zVKt7QFR0K3r2fWMgAAAAAAAAAPBhkAAAAAn9d2dEiOtEmrY00LgToW5O8yAAAAAAAA \
                 AA8GGQAAAACQhej3x994TLzLbzhluZ0aCjMAAAAAAAAADwYZAAAAAJ8tTs1ZUFBKqS0F1bsSZ8cz \
                 MwAAAAAAAAAPBhkAAAAAVC24CvRHy0qBjMxb8Oy2SVwzAAAAAAAAAA8GGQAAAAAyK5TpVS6XQbC9 \
                 X/WMuohghzMAAAAAAAAADwYZAAAAANbs3cZUIxlMkJswajBYSE6iMwAAAAAAAAAPBhkAAAAAEoKZ \
                 ugpG20S/tXG/CdHGi78zAAAAAAAAAA8GGQAAAACj4/W4M+0IRoHhN9bJ3P2c6zMAAAAAAAAADwYZ \
                 AAAAADgyHP4qQ6FDjiWX59HvEPMWNAAAAAAAAAAQBhkBAAAAZIpVeBnc/kOg0IB1sqNwoyc0AAAA \
                 AAAAABAGGQEAAABPt3jbHO+SSKv+Hma4Ix32OjQAAAAAAAAAEAYZAQAAAB1qLMdS8n5OvdE/yjQq \
                 yzVcNAAAAAAAAAAQBhkBAAAAakXu/4fNkEOOBxYUbGcv0H00AAAAAAAAABAGGQEAAAA95mwJrE+p \
                 SIKpYa6egA5fkjQAAAAAAAAAEAYZAQAAALWHjeUmgYBFgPuGGyL3kpavNAAAAAAAAAAQBhkBAAAA \
                 x5G0yhipYE+1Atq3XjNPQNA0AAAAAAAAABAGGQEAAADsG45FeoP2RbnVkl7V0pne8zQAAAAAAAAA \
                 EQUZAAAAAOeXSeEKgPdMrRDeS0W1eNsINQAAAAAAAAARBRkAAAAAbc2LqUNTA0aK/lkI5GEREh81 \
                 AAAAAAAAABEFGQAAAADBRfLrqCmvTZyxON/GCKjINjUAAAAAAAAAEQUZAAAAAEgY2xjgEmdBudfa \
                 f82lB9tPNQAAAAAAAAARBRkAAAAAr4sBECHOYECAvUf+dO1Nq3Y1AAAAAAAAABEFGQAAAACI5KNc \
                 rtuuT4KCqY+80hEmnzUAAAAAAAAAEQUZAAAAAL/WTsDIVUdLn45aHzHO7mDCNQAAAAAAAAASBRkB \
                 AAAAoJBzGfZllUq9xFXVijsCU9E1AAAAAAAAABIFGQEAAACihFWdhS2aQZgsoAiIu53f4jUAAAAA \
                 AAAAEgUZAQAAANT8YIh7pyBKkEWhUP8R1gkCNgAAAAAAAAASBRkBAAAAt9c1rzVQY0uJcvC3R7n0 \
                 3CE2AAAAAAAAABIFGQEAAACjGACgD/IyRr98japTUckUNDYAAAAAAAAAEgUZAQAAAAnlLq40G8BB \
                 rLdtRlAWiRVPNgAAAAAAAAATBBkAAAAACO27Rnuc/EimFJUlBXP06mQ2AAAAAAAAABMEGQAAAAAF \
                 1rYcsxEUTrsw2pHI45g6ezYAAAAAAAAAEwQZAAAAAICZLrnVuSFInJQUD2MvYxKSNgAAAAAAAAAT \
                 BBkAAAAAKRUEWvj+B02wb7WbVzsy0qk2AAAAAAAAABMEGQAAAAANmqBUe9UQTItpqELWWQrVwjYA \
                 AAAAAAAAEwQZAAAAAKrTbaq0wuJApUSmu7P1w5XbNgAAAAAAAAATBBkAAAAAlnhT2283rkikklPQ \
                 VHdz0Ow2AAAAAAAAABMEGQAAAABqKajhN9vRRIzOe8lh1ZxUCDcAAAAAAAAAEwQZAAAAAAYWPU/q \
                 PwFMvjyNZxxAHjskNwAAAAAAAAAUBBkAAAAAwi1oLGiLY0+hZa4pHUzxODs3AAAAAAAAABQEGQAA \
                 AAAI/9jP18ArRZ9g71xwwyCUVDcAAAAAAAAAFAQZAAAAAFBJ9dTyJrRPuiH/qxavyt5tNwAAAAAA \
                 AAAUBBkAAAAApGvbIXuaFEqeKWSmDFkwHYg3AAAAAAAAABUGBQAAAABEEwkApB43T7eJAXULppiM \
                 qjcAAAAAAAAAFQYFAAAAAE4EyrNYo2hNmIOqopQaypnMNwAAAAAAAAAVBgUAAAAAvqJDt9Ro002v \
                 MpJCW3u2I+w3AAAAAAAAABUGBQAAAACmWzaPucEjQpj8KCoHVqPtETgAAAAAAAAAFgUFAAAAAGA9 \
                 ZNNCDC1Bp9ZS5mNTJ/YwOAAAAAAAAAAWBQUAAAAAQez18FUNMkevAkQKRKPPD084AAAAAAAAABYF \
                 BQAAAACDHP2V9X1KSb6LEwDhydHNbDgAAAAAAAAAFgUFAAAAAMeGVH0g4XFHt/F7VsbTFwyTOAAA \
                 AAAAAAAWBQUAAAAAXFFy94cO1UimduaWLD4Rlbs4AAAAAAAAABcEBQAAAADZi4unF4D1TbhqCfdW \
                 r/p82jgAAAAAAAAAFwQFAAAAAPOMoc2Wwa1GsolgwHKGmZT1OAAAAAAAAAAXBAUAAAAAuR9TaBFV \
                 iUmXvtEaD1VjPxg5AAAAAAAAABgEBQAAAAA9Kw5i5wn9QoAqF6E2Uv56ODkAAAAAAAAAGAQFAAAA \
                 ABvmgnSJxX9LjsxG1FWsO4daOQAAAAAAAAAZBAUAAAAAHIUmin4c00imh/vKm5rBa3w5AAAAAAAA \
                 ABkEBQAAAAB8n/rdnvC5QIwavod6mn9LqjkAAAAAAAAAGgQFAAAAAFYR+3odLPxAsmCqt0QrYv7C \
                 OQAAAAAAAAAaBAUAAAAA1EIlrVSRbUyKRDDxHulpieY5AAAAAAAAABsEBQAAAADQ4wEkCsVYS4ey \
                 fnlLfSYHAzoAAAAAAAAAGwQFAAAAAJBNr8G80cpEhdQAO6M9s7kwOgAAAAAAAAAbBAUAAAAACkmY \
                 gdCtskezujFrEtZHtE86AAAAAAAAABsEBQAAAAAg4rZoCc9rRpLTRc2WS5UJfjoAAAAAAAAAHAQF \
                 AAAAAHfvCf1HVv9OgJyvK2RlmkWdOgAAAAAAAAAcBAUAAAAAaxfvAQ0+KkK0+E6ogANej8w6AAAA \
                 AAAAABwEBQAAAABy6OeMjBiYS52Q+PkLeq0C9zoAAAAAAAABHQQFAAABAHDU5c47bsxPjCvRdChW \
                 ip8KOwAAAAAAAAEdBAUAAAEAuNBHiTvD4UOMVptnTAUoMhw7AAAAAAAAAR0EBQAAAQA5ZmvK1kqu \
                 QKV1FN7gf2QwLzsAAAAAAAABHQQFAAABAECW7Qkg8ApArNjX2Gff2cJEOwAAAAAAAAEdBAUAAAEA \
                 SU497z2lgU2isSymwlVrLFg7AAAAAAAAAR0EBQAAAQBcb1irVlIyRpYv/v2LSeb0bDsAAAAAAAAB \
                 HQQFAAABAJLBt+yrc+1NrPQjmbCV0MyAOwAAAAAAAAEdBAUAAAEAHTtZRbHfkU67+y1dDOIiepQ7 \
                 AAAAAAAAAR0EBQAAAQBgdzJvXIx8QZthg2qYKH4MqzsAAAAAAAABHQQFAAABAPc/E98Uv5VPr+N7 \
                 SOfjMe/JOwAAAAAAAAEdBAUAAAEAYb/HXclelkmcy9+Aai0O/uE7AAAAAAAAAR0EBQAAAQB1Twy1 \
                 m1noQ43NEIGnlnJB/jsAAAAAAAABHQQFAAABAIeeUOqhB0VKntzrpaOfNq8UPAAAAAAAAAEdBAUA \
                 AAEAeKainWv7Z06rhGDdapyBmjY8AAAAAAAAAR0EBQAAAQAFYSOSZ7tPSZTHf3pgeSm9SzwAAAAA \
                 AAABHQQFAAABAJw4WOXDgylLrf5eTX9Gw1hlPAAAAAAAAAEdBAUAAAEA/zPYnpJPNk+zcIaDpPEy \
                 dXs8AAAAAAAAAR0EBQAAAQDngggt56Q7QozMcNkeAVixljwAAAAAAAABHQQFAAABACxi527YGAVA \
                 n7eS22RKJ5unPAAAAAAAAAIeBQUAAAIAUh1G9yt8skOHROqVjgvQmro8AAAAAAAAAh4FBQAAAgBA \
                 gAujitY/QrC1nOKS6lqPzDwAAAAAAAACHgUFAAACAOMRnxtcyBtOuymHmtLJCePhPAAAAAAAAAIe \
                 BQUAAAIAaxyY3I78D0KqQ/jzPlwJI/I8AAAAAAAAAh4FBQAAAgDm8+Hvoq5EQaIIMqqHK2VFBD0A \
                 AAAAAAACHgUFAAACAPo6HHfFUD9EsVH/JUbYY6AYPQAAAAAAAAIeBQUAAAIASSZ2jNGXU0mtJ7fi \
                 wluXLiw9AAAAAAAAAh4FBQAAAgCc2iKz4qJYQJ5O9ZppcL1pQz0AAAAAAAACHgUFAAACAEoSXUog \
                 5rpEtv9liWGzO5phPQAAAAAAAAIeBQUAAAIA0Sh6QnzRv0q3FzLHgLpvB3k9AAAAAAAAAh4FBQAA \
                 AgDxn8cAUGg9RL9hcc3g3jBflj0AAAAAAAACHgUFAAACADj7OrF5zeVKn3/u0FjXUMqsPQAAAAAA \
                 AAIeBQUAAAIADsE64dB1/0qgzXZJgs9UHME9AAAAAAAAAh4FBQAAAgDw+k6sH/hhT7336jKwKrEX \
                 1z0AAAAAAAACHgUFAAACAMax9dmGU1pJiPma1rQaybPyPQAAAAAAAAIeBQUAAAIADPzAZ7reG0C/ \
                 i5yK2DlYBAM+AAAAAAAAAh8GBQAAAwA2XebDHxQvTaMDqELudWopFj4AAAAAAAACHwYFAAADAMu8 \
                 qpyxYUtLi+zRCjw6ws4oPgAAAAAAAAIfBgUAAAMAbuoU6fqlOUSjlKm7MpPKCTo+AAAAAAAAAh8G \
                 BQAAAwBZzsrY0jPHSpsbm3IznFHITj4AAAAAAAACHwYFAAADAGWSnewendBOg4rNwg8lUaFiPgAA \
                 AAAAAAIfBgUAAAMAuhsL15O4REWW4rejGAkcM3Y+AAAAAAAAAh8GBQAAAwBvWVDUTYngSZZq/Tnt \
                 TExkjT4AAAAAAAACHwYFAAADAJdBQU/CDwFMtoqGy7msJUyrPgAAAAAAAAIfBgUAAAMAEIGbgm8O \
                 SUO8pEKANXd4jcM+AAAAAAAAAh8GBQAAAwC82n3avj9HRJ4BardEC0zU3z4AAAAAAAACHwYFAAAD \
                 AEXKustqVRZErQO9pZjqp8j8PgAAAAAAAAIfBgUAAAMAywYaBLjFckeAn0FtA9FmVB0/AAAAAAAA \
                 Ah8GBQAAAwDhTuCDjfptQ4mU0xqGLKt3Mz8AAAAAAAACHwYFAAADAD2i397RbqZFhdxjyuBUbeZS \
                 PwAAAAAAAAIfBgUAAAMAwQHza0q56UO6MdSUWYxH+2c/AAAAAAAAAh8GBQAAAwDjqzSyVwicT7Ba \
                 TcMU+FVXfT8AAAAAAAACHwYFAAADACF4KqonGCxMjx1FE6NN2peXPwAAAAAAAAIfBgUAAAMAIOYf \
                 NvRktUG6d4T44Hmx97I/AAAAAAAAAh8GBQAAAwDfuhG7qtgOR5MRIOr4D+XM0T8AAAAAAAACHwYF \
                 AAADAIWIyAuMcR1Jkh9vIUNJ55ziPwAAAAAAAAIfBgUAAAMADE18/IUuuUuv1AHtFHa16QhAAAAA \
                 AAAAAh8GBQAAAwAZZg9Qk+91S7y0goGZmKPKKEAAAAAAAAACHwYFAAADAOvOm5425yZPiN52P4fc \
                 xIVGQAAAAAAAAAIgBgUAAAUA6VR4I/x5l0SgwacJaWkca1lAAAAAAAAAAiAGBQAABQABo/jI9Rky \
                 QZbOLenUrb0za0AAAAAAAAACIAYFAAAFAGH9MTFPXghDjW1ivhmHySx/QAAAAAAAAAIgBgUAAAUA \
                 X4vdhaTq80qmKMzp53yaA5ZAAAAAAAAAAiAGBQAABQA/v6IsnpRqRILH4loV7HjEtEAAAAAAAAAC \
                 IAYFAAAFAOPwdxeSc5hBl+qK5N5vY4HMQAAAAAAAAAIgBgUAAAUAykw+nXLh8Uai9B0hBwUUROlA \
                 AAAAAAAAAiAGBQAABQBubExzurCYQqiRZxdysr0b/0AAAAAAAAACIAYFAAAFAEunEmn7pRpAv9su \
                 OrRvSwIeQQAAAAAAAAIgBgUAAAUAj/BcWxq4HUOwgDRQ2GIFZTNBAAAAAAAAAiAGBQAABQDzfW3g \
                 0KqdQY37CsN+K985SUEAAAAAAAACIAYFAAAFAP40mAXqqP9LtntNAGtUR9NkQQAAAAAAAAIgBgUA \
                 AAUAaC37892Di0yPCQjg2VCsO3VBAAAAAAAAAiAGBQAABQAbOwl2V3DXSblwY468v9hzm0EAAAAA \
                 AAACIAYFAAAFAHRBtKNRJNZMsl9mY4v7kEa7QQAAAAAAAAIgBgUAAAUA2CnkH6c/OUq28APd7UL+ \
                 FNlBAAAAAAAAAiEGBQAABgD873Hq8WklSZmRL14xm7wk8UEAAAAAAAACIQYFAAAGAEyeeaU8+G5M \
                 lRbf6baWFQsIQgAAAAAAAAIhBgUAAAYAw2wWbl1JikOJ59fJ5v1N6iFCAAAAAAAAAiEGBQAABgAY \
                 Ptv776izT5GD3/1gvQmEPUIAAAAAAAACIQYFAAAGAFkRiHZcFeBDnbctcKmjpMpgQgAAAAAAAAIh \
                 BgUAAAYABCfXbVL3cUuUxxHOxr/DVXhCAAAAAAAAAiEGBQAABgAfUmaqcCPYSqK7wJXj5DOPlUIA \
                 AAAAAAACIQYFAAAGAK+pMh90Er1Iuh4at1CKI+iwQgAAAAAAAAIhBgUAAAYAxUUKCJ+f60m0sMPG \
                 EKXr09RCAAAAAAAAAiEGBQAABgCarGH7iBbSRY9rBnTb/6M87kIAAAAAAAACIQYFAAAGAJfn/HKE \
                 GN1IqGCy9qXv08oJQwAAAAAAAAIhBgUAAAYA6oriq1pisUOOMCJeuPvZ5SlDAAAAAAAAAiEGBQAA \
                 BgCDoO38AxIqQI7EPX7Z82SMP0MAAAAAAAACIQYFAAAGAMgN6qrheENDnyW2m4PdG85lQwAAAAAA \
                 AAIhBgUAAAYASdi0Sryq+0OH7jrtAlGIkYVDAAAAAAAAAiEGBQAABgCn+uly0eo9T59uOrwJCoHX \
                 o0MAAAAAAAACIgYFAAAHAMOiu8v1D1hFhGoEPvnXhVm7QwAAAAAAAAIiBgUAAAcAKhXzvgSK8kCg \
                 ZTQMPyNRbdJDAAAAAAAAAiIGBQAABwCkJja2BV/tTJY5MbpzChJ+60MAAAAAAAACIgYFAAAHAMGP \
                 No1wlOJLjWaQ6DbLsFEHRAAAAAAAAAIiBgUAAAcAda8Q9beKJkSiNhv7lcNP+CpEAAAAAAAAAiIG \
                 BQAABwAnTxSfxSq5QImdiYwri0+BQkQAAAAAAAACIgYFAAAHAAopAgCRICRDnlM8/iiITN5fRAAA \
                 AAAAAAIiBgUAAAcAT5Csu35qikG7SyTIXaBhh4NEAAAAAAAAAiIGBQAABwCRcBj6RoKxR5ZPgKCx \
                 5daanUQAAAAAAAACIgYFAAAHAHCkP5JxqotLs1w2t5v59Eu4RAAAAAAAAAIiBgUAAAcAAe3t0IEI \
                 N0uXOBkEAAlQmNhEAAAAAAAAAiIGBQAABwCmJgAAAAAAAIDuKmYAAAAA9GUAABwOAAAHAAAAAAAA \
                 AMQmAAAAAAAAALO+YAAAAAB8TwAAHA4AAAcAAAAAAAAA2CYAAAAAAAAAtbJbAAAAAGNFAAAcDgAA \
                 BwAAAAAAAAD2JgAAAAAAAIDin1cAAAAAOTgAABwOAAAHAAAAAAAAABQnAAAAAAAAgChfUgAAAACA \
                 JQAAARkAAAcAAAAAAAAAMScAAAAAAACAREVQAAAAAPAjAAAyFQAABwAAAAAAAABJJwAAAAAAAID8 \
                 Yk0AAAAAsR0AAAHXAAAGAAAAAAAAAGgnAAAAAAAAADEbSgAAAAByFwAAAdcAAAYAAAAAAAAAMDM2 \
                 MTItMDQ5MTktMDExLTkzOTc5NC0wMy0xMDMzLTI2MTAwLjAwMDAtMzIxMjAyNABXaW5kb3dzAFdp \
                 bmRvd3MgU2VydmVyIDIwMjUAMDM2MTItMDAwOTYtMjA4LTg0OTU3OC0wMy0xMDMzLTI2MTAwLjAw \
                 MDAtMzIxMjAyNABPZmZpY2UyMDEwAE9mZmljZSAyMDEwADAzNjEyLTAwMjA2LTI1NC00Mjk2OTct \
                 MDMtMTAzMy0yNjEwMC4wMDAwLTMyMTIwMjQAT2ZmaWNlMjAxMwBPZmZpY2UgMjAxMwAwMzYxMi0w \
                 MDIwNi00NTItNTg2ODI5LTAzLTEwMzMtMjYxMDAuMDAwMC0zMjEyMDI0AE9mZmljZTIwMTYAT2Zm \
                 aWNlIDIwMTYAMDM2MTItMDM4NTgtMzA5LTY5NTc4MC0wMy0xMDMzLTI2MTAwLjAwMDAtMzIxMjAy \
                 NABXaW5DaGluYUdvdgBXaW5kb3dzIDEwIENoaW5hIEdvdmVybm1lbnQAMDM2MTItMDAyMDYtNjg1 \
                 LTA3NDQzOC0wMy0xMDMzLTI2MTAwLjAwMDAtMzIxMjAyNABPZmZpY2UyMDE5AE9mZmljZSAyMDE5 \
                 ADAzNjEyLTAwMjA2LTU3OS02MDAwMjAtMDMtMTAzMy0yNjEwMC4wMDAwLTMyMTIwMjQAT2ZmaWNl \
                 MjAyMQBPZmZpY2UgMjAyMQAwMzYxMi0wMDIwNi02MDctMTA4MDExLTAzLTEwMzMtMjYxMDAuMDAw \
                 MC0zMjEyMDI0AE9mZmljZTIwMjQAT2ZmaWNlIDIwMjQAV2luZG93cyAxMSAyNEgyIC8gU2VydmVy \
                 IDIwMjUAV2luZG93cyBTZXJ2ZXIgMjAyMgBXaW5kb3dzIDEwIDE4MDkgLyBTZXJ2ZXIgMjAxOQBX \
                 aW5kb3dzIDEwIDE2MDcgLyBTZXJ2ZXIgMjAxNgBXaW5kb3dzIDguMSAvIFNlcnZlciAyMDEyIFIy \
                 AFdpbmRvd3MgOCAvIFNlcnZlciAyMDEyAFdpbmRvd3MgNyAvIFNlcnZlciAyMDA4IFIyIFNQMQBX \
                 aW5kb3dzIFZpc3RhIC8gU2VydmVyIDIwMDggU1AyAFdpbmRvd3MAT2ZmaWNlMjAxMABPZmZpY2Uy \
                 MDEzKwBXaW5kb3dzIFNlcnZlciAyMDI1AFdpbmRvd3MgU2VydmVyIDIwMjIAV2luZG93cyBTZXJ2 \
                 ZXIgMjAxOQBXaW5kb3dzIFNlcnZlciAyMDE2AFdpbmRvd3MgMTAgMjAyNCAoVm9sdW1lKQBXaW5k \
                 b3dzIDEwIDIwMjEgKFZvbHVtZSkAV2luZG93cyAxMCAyMDE1IChWb2x1bWUpAFdpbmRvd3MgMTAg \
                 U2VydmVyUmRzaCAoVm9sdW1lKQBXaW5kb3dzIDEwIENoaW5hIEdvdmVybm1lbnQAV2luZG93cyAx \
                 MCAyMDE5IChWb2x1bWUpAFdpbmRvd3MgMTAgMjAxNiAoVm9sdW1lKQBXaW5kb3dzIDEwIChWb2x1 \
                 bWUpAFdpbmRvd3MgMTAgKFJldGFpbCkAV2luZG93cyBQcmV2aWV3AFdpbmRvd3MgU2VydmVyIFBy \
                 ZXZpZXcAV2luZG93cyA4LjEgKFZvbHVtZSkAV2luZG93cyA4LjEgKFJldGFpbCkAV2luZG93cyA4 \
                 IChWb2x1bWUpAFdpbmRvd3MgOCAoUmV0YWlsKQBXaW5kb3dzIDcAV2luZG93cyBWaXN0YQBXaW5k \
                 b3dzIFNlcnZlciAyMDEyIFIyAFdpbmRvd3MgU2VydmVyIDIwMTIAV2luZG93cyBTZXJ2ZXIgMjAw \
                 OCBSMiBBIChXZWIgYW5kIEhQQykAV2luZG93cyBTZXJ2ZXIgMjAwOCBSMiBCIChTdGFuZGFyZCBh \
                 bmQgRW50ZXJwcmlzZSkAV2luZG93cyBTZXJ2ZXIgMjAwOCBSMiBDIChEYXRhY2VudGVyKQBXaW5k \
                 b3dzIFNlcnZlciAyMDA4IEEgKFdlYiBhbmQgSFBDKQBXaW5kb3dzIFNlcnZlciAyMDA4IEIgKFN0 \
                 YW5kYXJkIGFuZCBFbnRlcnByaXNlKQBXaW5kb3dzIFNlcnZlciAyMDA4IEMgKERhdGFjZW50ZXIp \
                 AE9mZmljZSAyMDEwAE9mZmljZSAyMDEzAE9mZmljZSAyMDE2AE9mZmljZSAyMDE5AE9mZmljZSAy \
                 MDIxAE9mZmljZSAyMDI0AFdpbmRvd3MgU2VydmVyIDIwMjUgQXp1cmUgQ29yZQBXaW5kb3dzIFNl \
                 cnZlciAyMDI1IERhdGFjZW50ZXIgQXp1cmUgRWRpdGlvbgBXaW5kb3dzIFNlcnZlciAyMDI1IERh \
                 dGFjZW50ZXIAV2luZG93cyBTZXJ2ZXIgMjAyNSBTdGFuZGFyZABXaW5kb3dzIFNlcnZlciAyMDIy \
                 IEF6dXJlIENvcmUAV2luZG93cyBTZXJ2ZXIgMjAyMiBEYXRhY2VudGVyIEF6dXJlIEVkaXRpb24A \
                 V2luZG93cyBTZXJ2ZXIgMjAyMiBEYXRhY2VudGVyAFdpbmRvd3MgU2VydmVyIDIwMjIgU3RhbmRh \
                 cmQAV2luZG93cyBTZXJ2ZXIgMjAyMiBEYXRhY2VudGVyIChTZW1pLUFubnVhbCBDaGFubmVsKQBX \
                 aW5kb3dzIFNlcnZlciAyMDIyIFN0YW5kYXJkIChTZW1pLUFubnVhbCBDaGFubmVsKQBXaW5kb3dz \
                 IFNlcnZlciAyMDE5IEF6dXJlIENvcmUAV2luZG93cyBTZXJ2ZXIgMjAxOSBFc3NlbnRpYWxzAFdp \
                 bmRvd3MgU2VydmVyIDIwMTkgRGF0YWNlbnRlcgBXaW5kb3dzIFNlcnZlciAyMDE5IFN0YW5kYXJk \
                 AFdpbmRvd3MgU2VydmVyIDIwMTkgQVJNNjQAV2luZG93cyBTZXJ2ZXIgMjAxOSBEYXRhY2VudGVy \
                 IChTZW1pLUFubnVhbCBDaGFubmVsKQBXaW5kb3dzIFNlcnZlciAyMDE5IFN0YW5kYXJkIChTZW1p \
                 LUFubnVhbCBDaGFubmVsKQBXaW5kb3dzIFNlcnZlciAyMDE2IEF6dXJlIENvcmUAV2luZG93cyBT \
                 ZXJ2ZXIgMjAxNiBFc3NlbnRpYWxzAFdpbmRvd3MgU2VydmVyIDIwMTYgRGF0YWNlbnRlcgBXaW5k \
                 b3dzIFNlcnZlciAyMDE2IFN0YW5kYXJkAFdpbmRvd3MgU2VydmVyIDIwMTYgQVJNNjQAV2luZG93 \
                 cyBTZXJ2ZXIgMjAxNiBEYXRhY2VudGVyIChTZW1pLUFubnVhbCBDaGFubmVsKQBXaW5kb3dzIFNl \
                 cnZlciAyMDE2IFN0YW5kYXJkIChTZW1pLUFubnVhbCBDaGFubmVsKQBXaW5kb3dzIFNlcnZlciAy \
                 MDE2IENsb3VkIFN0b3JhZ2UAV2luZG93cyAxMC8xMSBFbnRlcnByaXNlIG11bHRpLXNlc3Npb24A \
                 V2luZG93cyAxMC8xMSBFbnRlcnByaXNlIEcAV2luZG93cyAxMC8xMSBFbnRlcnByaXNlIEcgTgBX \
                 aW5kb3dzIDEwLzExIEVudGVycHJpc2UgTFRTQyAyMDE5LTIwMjEtMjAyNABXaW5kb3dzIDEwLzEx \
                 IEVudGVycHJpc2UgTFRTQyAyMDE5LTIwMjEtMjAyNCBOAFdpbmRvd3MgMTAgRW50ZXJwcmlzZSAy \
                 MDE2IExUU0IAV2luZG93cyAxMCBFbnRlcnByaXNlIDIwMTYgTFRTQiBOAFdpbmRvd3MgMTAgRW50 \
                 ZXJwcmlzZSAyMDE1IExUU0IAV2luZG93cyAxMCBFbnRlcnByaXNlIDIwMTUgTFRTQiBOAFdpbmRv \
                 d3MgMTAvMTEgRWR1Y2F0aW9uAFdpbmRvd3MgMTAvMTEgRWR1Y2F0aW9uIE4AV2luZG93cyAxMC8x \
                 MSBFbnRlcnByaXNlAFdpbmRvd3MgMTAvMTEgRW50ZXJwcmlzZSBOAFdpbmRvd3MgMTAvMTEgUHJv \
                 AFdpbmRvd3MgMTAvMTEgUHJvIE4AV2luZG93cyAxMC8xMSBQcm8gRWR1Y2F0aW9uAFdpbmRvd3Mg \
                 MTAvMTEgUHJvIEVkdWNhdGlvbiBOAFdpbmRvd3MgMTAvMTEgUHJvIFdvcmtzdGF0aW9uAFdpbmRv \
                 d3MgMTAvMTEgUHJvIFdvcmtzdGF0aW9uIE4AV2luZG93cyAxMC8xMSBJb1QgRW50ZXJwcmlzZSBM \
                 VFNDIDIwMjEtMjAyNABXaW5kb3dzIDExIFNFAFdpbmRvd3MgMTEgU0UgTgBXaW5kb3dzIDEwIFMg \
                 KExlYW4pAFdpbmRvd3MgMTAgUmVtb3RlIFNlcnZlcgBXaW5kb3dzIDEwLzExIEhvbWUAV2luZG93 \
                 cyAxMC8xMSBIb21lIE4AV2luZG93cyAxMC8xMSBIb21lIENvdW50cnkgU3BlY2lmaWMAV2luZG93 \
                 cyAxMC8xMSBIb21lIFNpbmdsZSBMYW5ndWFnZQBXaW5kb3dzIDgvMTAgUHJldmlldyBFbnRlcnBy \
                 aXNlAFdpbmRvd3MgOC8xMCBQcmV2aWV3IFByb2Zlc3Npb25hbABXaW5kb3dzIDgvMTAgUHJldmll \
                 dyBQcm9mZXNzaW9uYWxXTUMAV2luZG93cyA4LzEwIFByZXZpZXcgQ29yZQBXaW5kb3dzIDgvMTAg \
                 UHJldmlldyBDb3JlQVJNAFdpbmRvd3MgU2VydmVyIFByZXZpZXcgRGF0YWNlbnRlcgBXaW5kb3dz \
                 IFNlcnZlciBQcmV2aWV3IFN0YW5kYXJkAFdpbmRvd3MgU2VydmVyIFByZXZpZXcgV2ViAFdpbmRv \
                 d3MgU2VydmVyIFByZXZpZXcgU2VydmVySEkAV2luZG93cyA4LjEgRW50ZXJwcmlzZQBXaW5kb3dz \
                 IDguMSBFbnRlcnByaXNlIE4AV2luZG93cyA4LjEgUHJvZmVzc2lvbmFsAFdpbmRvd3MgOC4xIFBy \
                 b2Zlc3Npb25hbCBOAFdpbmRvd3MgOC4xIEVtYmVkZGVkIEluZHVzdHJ5IEF1dG9tb3RpdmUAV2lu \
                 ZG93cyA4LjEgRW1iZWRkZWQgSW5kdXN0cnkgRW50ZXJwcmlzZQBXaW5kb3dzIDguMSBFbWJlZGRl \
                 ZCBJbmR1c3RyeSBQcm9mZXNzaW9uYWwAV2luZG93cyA4LjEgQ29yZSBDb25uZWN0ZWQAV2luZG93 \
                 cyA4LjEgQ29yZSBDb25uZWN0ZWQgTgBXaW5kb3dzIDguMSBDb3JlIENvbm5lY3RlZCBDb3VudHJ5 \
                 IFNwZWNpZmljAFdpbmRvd3MgOC4xIENvcmUgQ29ubmVjdGVkIFNpbmdsZSBMYW5ndWFnZQBXaW5k \
                 b3dzIDguMSBDb3JlAFdpbmRvd3MgOC4xIENvcmUgTgBXaW5kb3dzIDguMSBDb3JlIENvdW50cnkg \
                 U3BlY2lmaWMAV2luZG93cyA4LjEgQ29yZSBTaW5nbGUgTGFuZ3VhZ2UAV2luZG93cyA4LjEgQ29y \
                 ZSBBUk0AV2luZG93cyA4LjEgUHJvZmVzc2lvbmFsIFdNQwBXaW5kb3dzIDguMSBQcm9mZXNzaW9u \
                 YWwgU3R1ZGVudABXaW5kb3dzIDguMSBQcm9mZXNzaW9uYWwgU3R1ZGVudCBOAFdpbmRvd3MgOCBF \
                 bnRlcnByaXNlAFdpbmRvd3MgOCBFbnRlcnByaXNlIE4AV2luZG93cyA4IFByb2Zlc3Npb25hbABX \
                 aW5kb3dzIDggUHJvZmVzc2lvbmFsIE4AV2luZG93cyA4IEVtYmVkZGVkIEluZHVzdHJ5IEVudGVy \
                 cHJpc2UAV2luZG93cyA4IEVtYmVkZGVkIEluZHVzdHJ5IFByb2Zlc3Npb25hbABXaW5kb3dzIDgg \
                 RW1iZWRkZWQgUE9TUmVhZHkgW0JldGFdAFdpbmRvd3MgOCBDb3JlAFdpbmRvd3MgOCBDb3JlIE4A \
                 V2luZG93cyA4IENvcmUgQ291bnRyeSBTcGVjaWZpYwBXaW5kb3dzIDggQ29yZSBTaW5nbGUgTGFu \
                 Z3VhZ2UAV2luZG93cyA4IENvcmUgQVJNAFdpbmRvd3MgOCBQcm9mZXNzaW9uYWwgV01DAFdpbmRv \
                 d3MgNyBFbnRlcnByaXNlAFdpbmRvd3MgNyBFbnRlcnByaXNlIEUAV2luZG93cyA3IEVudGVycHJp \
                 c2UgTgBXaW5kb3dzIDcgUHJvZmVzc2lvbmFsAFdpbmRvd3MgNyBQcm9mZXNzaW9uYWwgRQBXaW5k \
                 b3dzIDcgUHJvZmVzc2lvbmFsIE4AV2luZG93cyA3IFRoaW5QQwBXaW5kb3dzIDcgRW1iZWRkZWQg \
                 UE9TUmVhZHkAV2luZG93cyA3IEVtYmVkZGVkIFN0YW5kYXJkAFdpbmRvd3MgVmlzdGEgQnVzaW5l \
                 c3MAV2luZG93cyBWaXN0YSBCdXNpbmVzcyBOAFdpbmRvd3MgVmlzdGEgRW50ZXJwcmlzZQBXaW5k \
                 b3dzIFZpc3RhIEVudGVycHJpc2UgTgBXaW5kb3dzIFNlcnZlciAyMDEyIFIyIEVzc2VudGlhbHMA \
                 V2luZG93cyBTZXJ2ZXIgMjAxMiBSMiBEYXRhY2VudGVyAFdpbmRvd3MgU2VydmVyIDIwMTIgUjIg \
                 U3RhbmRhcmQAV2luZG93cyBTZXJ2ZXIgMjAxMiBSMiBDbG91ZCBTdG9yYWdlAFdpbmRvd3MgU2Vy \
                 dmVyIDIwMTIgRXNzZW50aWFscwBXaW5kb3dzIFNlcnZlciAyMDEyIERhdGFjZW50ZXIAV2luZG93 \
                 cyBTZXJ2ZXIgMjAxMiBTdGFuZGFyZABXaW5kb3dzIFNlcnZlciAyMDEyIE11bHRpUG9pbnQgUHJl \
                 bWl1bQBXaW5kb3dzIFNlcnZlciAyMDEyIE11bHRpUG9pbnQgU3RhbmRhcmQAV2luZG93cyBNdWx0 \
                 aVBvaW50IFNlcnZlciAyMDEwAFdpbmRvd3MgU2VydmVyIDIwMDggUjIgV2ViAFdpbmRvd3MgU2Vy \
                 dmVyIDIwMDggUjIgSFBDIEVkaXRpb24AV2luZG93cyBTZXJ2ZXIgMjAwOCBSMiBTdGFuZGFyZABX \
                 aW5kb3dzIFNlcnZlciAyMDA4IFIyIEVudGVycHJpc2UAV2luZG93cyBTZXJ2ZXIgMjAwOCBSMiBE \
                 YXRhY2VudGVyAFdpbmRvd3MgU2VydmVyIDIwMDggUjIgRW50ZXJwcmlzZSBmb3IgSXRhbml1bQBX \
                 aW5kb3dzIFNlcnZlciAyMDA4IFdlYgBXaW5kb3dzIFNlcnZlciAyMDA4IENvbXB1dGUgQ2x1c3Rl \
                 cgBXaW5kb3dzIFNlcnZlciAyMDA4IFN0YW5kYXJkAFdpbmRvd3MgU2VydmVyIDIwMDggU3RhbmRh \
                 cmQgd2l0aG91dCBIeXBlci1WAFdpbmRvd3MgU2VydmVyIDIwMDggRW50ZXJwcmlzZQBXaW5kb3dz \
                 IFNlcnZlciAyMDA4IEVudGVycHJpc2Ugd2l0aG91dCBIeXBlci1WAFdpbmRvd3MgU2VydmVyIDIw \
                 MDggRGF0YWNlbnRlcgBXaW5kb3dzIFNlcnZlciAyMDA4IERhdGFjZW50ZXIgd2l0aG91dCBIeXBl \
                 ci1WAFdpbmRvd3MgU2VydmVyIDIwMDggRW50ZXJwcmlzZSBmb3IgSXRhbml1bQBPZmZpY2UgQWNj \
                 ZXNzIDIwMTAAT2ZmaWNlIEV4Y2VsIDIwMTAAT2ZmaWNlIEdyb292ZSAyMDEwAE9mZmljZSBJbmZv \
                 UGF0aCAyMDEwAE9mZmljZSBNb25kbyAxIDIwMTAAT2ZmaWNlIE1vbmRvIDIgMjAxMABPZmZpY2Ug \
                 T25lTm90ZSAyMDEwAE9mZmljZSBPdXRMb29rIDIwMTAAT2ZmaWNlIFBvd2VyUG9pbnQgMjAxMABP \
                 ZmZpY2UgUHJvZmVzc2lvbmFsIFBsdXMgMjAxMABPZmZpY2UgUHJvamVjdCBQcm8gMjAxMABPZmZp \
                 Y2UgUHJvamVjdCBTdGFuZGFyZCAyMDEwAE9mZmljZSBQdWJsaXNoZXIgMjAxMABPZmZpY2UgU21h \
                 bGwgQnVzaW5lc3MgQmFzaWNzIDIwMTAAT2ZmaWNlIFN0YW5kYXJkIDIwMTAAT2ZmaWNlIFZpc2lv \
                 IFByZW1pdW0gMjAxMABPZmZpY2UgVmlzaW8gUHJvIDIwMTAAT2ZmaWNlIFZpc2lvIFN0YW5kYXJk \
                 IDIwMTAAT2ZmaWNlIFdvcmQgMjAxMABPZmZpY2UgQWNjZXNzIDIwMTMAT2ZmaWNlIEV4Y2VsIDIw \
                 MTMAT2ZmaWNlIEluZm9QYXRoIDIwMTMAT2ZmaWNlIEx5bmMgMjAxMwBPZmZpY2UgTW9uZG8gMjAx \
                 MwBPZmZpY2UgT25lTm90ZSAyMDEzAE9mZmljZSBPdXRMb29rIDIwMTMAT2ZmaWNlIFBvd2VyUG9p \
                 bnQgMjAxMwBPZmZpY2UgUHJvZmVzc2lvbmFsIFBsdXMgMjAxMwBPZmZpY2UgUHJvamVjdCBQcm8g \
                 MjAxMwBPZmZpY2UgUHJvamVjdCBTdGFuZGFyZCAyMDEzAE9mZmljZSBQdWJsaXNoZXIgMjAxMwBP \
                 ZmZpY2UgU3RhbmRhcmQgMjAxMwBPZmZpY2UgVmlzaW8gUHJvIDIwMTMAT2ZmaWNlIFZpc2lvIFN0 \
                 YW5kYXJkIDIwMTMAT2ZmaWNlIFdvcmQgMjAxMwBPZmZpY2UgQWNjZXNzIDIwMTYAT2ZmaWNlIEV4 \
                 Y2VsIDIwMTYAT2ZmaWNlIE1vbmRvIDIwMTYAT2ZmaWNlIE1vbmRvIFIgMjAxNgBPZmZpY2UgT25l \
                 Tm90ZSAyMDE2AE9mZmljZSBPdXRsb29rIDIwMTYAT2ZmaWNlIFBvd2VycG9pbnQgMjAxNgBPZmZp \
                 Y2UgUHJvZmVzc2lvbmFsIFBsdXMgMjAxNgBPZmZpY2UgUHJvamVjdCBQcm8gMjAxNgBPZmZpY2Ug \
                 UHJvamVjdCBQcm8gMjAxNiBDMlIAT2ZmaWNlIFByb2plY3QgU3RhbmRhcmQgMjAxNgBPZmZpY2Ug \
                 UHJvamVjdCBTdGFuZGFyZCAyMDE2IEMyUgBPZmZpY2UgUHVibGlzaGVyIDIwMTYAT2ZmaWNlIFNr \
                 eXBlIGZvciBCdXNpbmVzcyAyMDE2AE9mZmljZSBTdGFuZGFyZCAyMDE2AE9mZmljZSBWaXNpbyBQ \
                 cm8gMjAxNgBPZmZpY2UgVmlzaW8gUHJvIDIwMTYgQzJSAE9mZmljZSBWaXNpbyBTdGFuZGFyZCAy \
                 MDE2AE9mZmljZSBWaXNpbyBTdGFuZGFyZCAyMDE2IEMyUgBPZmZpY2UgV29yZCAyMDE2AE9mZmlj \
                 ZSBQcm9mZXNzaW9uYWwgUGx1cyAyMDE5IFByZXZpZXcAT2ZmaWNlIFByb2plY3QgUHJvIDIwMTkg \
                 UHJldmlldwBPZmZpY2UgVmlzaW8gUHJvIDIwMTkgUHJldmlldwBPZmZpY2UgQWNjZXNzIDIwMTkA \
                 T2ZmaWNlIEV4Y2VsIDIwMTkAT2ZmaWNlIE91dGxvb2sgMjAxOQBPZmZpY2UgUG93ZXJwb2ludCAy \
                 MDE5AE9mZmljZSBQcm9mZXNzaW9uYWwgUGx1cyAyMDE5AE9mZmljZSBQcm9qZWN0IFBybyAyMDE5 \
                 AE9mZmljZSBQcm9qZWN0IFN0YW5kYXJkIDIwMTkAT2ZmaWNlIFB1Ymxpc2hlciAyMDE5AE9mZmlj \
                 ZSBTa3lwZSBmb3IgQnVzaW5lc3MgMjAxOQBPZmZpY2UgU3RhbmRhcmQgMjAxOQBPZmZpY2UgVmlz \
                 aW8gUHJvIDIwMTkAT2ZmaWNlIFZpc2lvIFN0YW5kYXJkIDIwMTkAT2ZmaWNlIFdvcmQgMjAxOQBP \
                 ZmZpY2UgUHJvZmVzc2lvbmFsIFBsdXMgMjAyMSBQcmV2aWV3AE9mZmljZSBQcm9qZWN0IFBybyAy \
                 MDIxIFByZXZpZXcAT2ZmaWNlIFZpc2lvIFBybyAyMDIxIFByZXZpZXcAT2ZmaWNlIEFjY2VzcyBM \
                 VFNDIDIwMjEAT2ZmaWNlIEV4Y2VsIExUU0MgMjAyMQBPZmZpY2UgT3V0bG9vayBMVFNDIDIwMjEA \
                 T2ZmaWNlIFBvd2VycG9pbnQgTFRTQyAyMDIxAE9mZmljZSBMVFNDIFByb2Zlc3Npb25hbCBQbHVz \
                 IDIwMjEAT2ZmaWNlIFByb2plY3QgUHJvIDIwMjEAT2ZmaWNlIFByb2plY3QgU3RhbmRhcmQgMjAy \
                 MQBPZmZpY2UgUHVibGlzaGVyIExUU0MgMjAyMQBPZmZpY2UgU2t5cGUgZm9yIEJ1c2luZXNzIExU \
                 U0MgMjAyMQBPZmZpY2UgTFRTQyBTdGFuZGFyZCAyMDIxAE9mZmljZSBWaXNpbyBMVFNDIFBybyAy \
                 MDIxAE9mZmljZSBWaXNpbyBMVFNDIFN0YW5kYXJkIDIwMjEAT2ZmaWNlIFdvcmQgTFRTQyAyMDIx \
                 AE9mZmljZSBQcm9mZXNzaW9uYWwgUGx1cyAyMDI0IFByZXZpZXcAT2ZmaWNlIFByb2plY3QgUHJv \
                 IDIwMjQgUHJldmlldwBPZmZpY2UgVmlzaW8gUHJvIDIwMjQgUHJldmlldwBPZmZpY2UgQWNjZXNz \
                 IExUU0MgMjAyNABPZmZpY2UgRXhjZWwgTFRTQyAyMDI0AE9mZmljZSBPdXRsb29rIExUU0MgMjAy \
                 NABPZmZpY2UgUG93ZXJwb2ludCBMVFNDIDIwMjQAT2ZmaWNlIExUU0MgUHJvZmVzc2lvbmFsIFBs \
                 dXMgMjAyNABPZmZpY2UgUHJvamVjdCBQcm8gMjAyNABPZmZpY2UgUHJvamVjdCBTdGFuZGFyZCAy \
                 MDI0AE9mZmljZSBTa3lwZSBmb3IgQnVzaW5lc3MgTFRTQyAyMDI0AE9mZmljZSBMVFNDIFN0YW5k \
                 YXJkIDIwMjQAT2ZmaWNlIFZpc2lvIExUU0MgUHJvIDIwMjQAT2ZmaWNlIFZpc2lvIExUU0MgU3Rh \
                 bmRhcmQgMjAyNABPZmZpY2UgV29yZCBMVFNDIDIwMjQA | base64 -d > /vlmcsd.kmd


        EXPOSE 1688/tcp
        ENTRYPOINT [ "/usr/bin/vlmcsd", "-D", "-d", "-j", "/vlmcsd.kmd", "-e" ]
    ports:
      - "1688:1688"
    restart: always

